/* COMPANIES */
INSERT INTO COMPANIES (ID, NAME) VALUES (1, 'Marvel Comics');
INSERT INTO COMPANIES (ID, NAME) VALUES (2, 'DC Comics');
INSERT INTO COMPANIES (ID, NAME) VALUES (3, 'Marvel Studios');

/* SUPERHEROS */
INSERT INTO SUPERHEROS (ID, NAME, GENDER, COMPANY_ID) VALUES(1, 'Spiderman', 'M', 1);
INSERT INTO SUPERHEROS (ID, NAME, GENDER, COMPANY_ID) VALUES(2, 'Capitana Marvel', 'F', 3);
INSERT INTO SUPERHEROS (ID, NAME, GENDER, COMPANY_ID) VALUES(3, 'Aquaman', 'M', 2);
INSERT INTO SUPERHEROS (ID, NAME, GENDER, COMPANY_ID) VALUES(4, 'Batgirl', 'F', 2);
